variable "REGION" {}
variable "S3_NAME" {}
variable "LAMBDA_DESCRIPTION" {}
variable "LAMBDA_FUNCTION_NAME" {}
variable "ACCESS_KEY_ID" {}
variable "ACCESS_KEY_SECRET" {}
variable "ECR_SERVERLESS_REPOSITORY_NAME" {}
variable "ECR_FACTORIAL_REPOSITORY_NAME" {}
variable "DATABASE_USER" {}
variable "DATABASE_PASSWORD" {}
variable "DATABASE_NAME" {}